"""Reproduce the paper's theta-versus-AMG-levels diagnostic figure."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
GROUP_COLUMNS = ["split", "pattern", "epsilon", "refinement", "h"]
REQUIRED_COLUMNS = {
    "pattern",
    "epsilon",
    "refinement",
    "h",
    "theta",
    "n_levels",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot theta against normalized AMG hierarchy depth, together with "
            "per-test-case regression p-value and R-squared histograms."
        )
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=Path("datasets/small"),
        help="Dataset or mesh-family root containing diffusion_reports.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/theta_vs_nlevels"),
        help="Directory for figures and regression statistics.",
    )
    parser.add_argument(
        "--figure-name",
        default="theta_vs_nlevels.png",
        help="PNG figure filename.",
    )
    parser.add_argument(
        "--svg-name",
        default="theta_vs_nlevels.svg",
        help="SVG figure filename generated by matplotlib.",
    )
    parser.add_argument("--dpi", type=int, default=220, help="PNG resolution.")
    parser.add_argument(
        "--include-splits",
        nargs="+",
        default=["all"],
        choices=["all", "train", "test"],
        help="Dataset splits to include.",
    )
    return parser.parse_args()


def import_plotting_packages() -> tuple[Any, Any, Any, Any, Any]:
    os.environ.setdefault(
        "MPLCONFIGDIR", str(REPO_ROOT / ".matplotlib-cache")
    )
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
        import pandas as pd
        import scipy  # noqa: F401
        import seaborn as sns
        import statsmodels  # noqa: F401
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "The theta-vs-levels figure requires numpy, pandas, scipy, "
            "matplotlib, seaborn, and statsmodels. Install them with:\n"
            "  python3 -m pip install -r requirements-figures.txt\n"
            f"Missing package: {exc.name}"
        ) from exc
    return np, pd, plt, sns, matplotlib


def report_candidates(
    dataset_root: Path, splits: list[str]
) -> list[tuple[str, Path]]:
    if splits == ["all"]:
        return [
            ("all", dataset_root / "raw" / "diffusion_reports"),
            ("all", dataset_root / "diffusion_reports"),
        ]
    return [
        (split, dataset_root / split / "raw" / "diffusion_reports")
        for split in splits
    ]


def fallback_split_candidates(
    dataset_root: Path, splits: list[str]
) -> list[tuple[str, Path]]:
    if splits != ["all"]:
        return []
    return [
        (split, dataset_root / split / "raw" / "diffusion_reports")
        for split in ("train", "test")
    ]


def load_reports(
    dataset_root: Path, splits: list[str], pd: Any
) -> Any:
    frames = []
    for split, report_dir in report_candidates(dataset_root, splits):
        for path in sorted(report_dir.glob("*.csv")):
            frame = pd.read_csv(path)
            frame["split"] = split
            frame["source_file"] = str(path)
            frames.append(frame)

    if not frames:
        for split, report_dir in fallback_split_candidates(
            dataset_root, splits
        ):
            for path in sorted(report_dir.glob("*.csv")):
                frame = pd.read_csv(path)
                frame["split"] = split
                frame["source_file"] = str(path)
                frames.append(frame)

    if not frames:
        raise FileNotFoundError(
            f"No diffusion report CSVs found below {dataset_root}."
        )

    data = pd.concat(frames, ignore_index=True)
    missing = REQUIRED_COLUMNS.difference(data.columns)
    if missing:
        raise ValueError(
            f"Missing required report columns: {sorted(missing)}. "
            "Rerun the experiments so their records contain amg_levels, then "
            "regenerate diffusion_reports/trials.csv."
        )

    numeric_columns = ["epsilon", "refinement", "h", "theta", "n_levels"]
    for column in numeric_columns:
        data[column] = pd.to_numeric(data[column], errors="raise")
    return data


def add_normalized_levels(data: Any) -> tuple[Any, bool]:
    data = data.copy()
    minimum = float(data["n_levels"].min())
    maximum = float(data["n_levels"].max())
    constant_depth = maximum == minimum
    if constant_depth:
        data["normalized_levels"] = 0.5
    else:
        data["normalized_levels"] = (
            data["n_levels"] - minimum
        ) / (maximum - minimum)
    return data, constant_depth


def regression_by_test_case(data: Any, pd: Any) -> Any:
    import statsmodels.api as sm

    records: list[dict[str, Any]] = []
    for key, group in data.groupby(GROUP_COLUMNS, dropna=False):
        # Timing repeats are duplicate observations for hierarchy depth. Reduce
        # them to one value per theta so they do not artificially strengthen
        # the regression significance.
        points = (
            group.groupby("theta", as_index=False)["normalized_levels"]
            .mean()
            .sort_values("theta")
        )
        if (
            points["theta"].nunique() < 3
            or points["normalized_levels"].nunique() < 2
        ):
            continue
        design = sm.add_constant(points["theta"], has_constant="add")
        result = sm.OLS(
            points["normalized_levels"], design
        ).fit()
        records.append(
            {
                **dict(zip(GROUP_COLUMNS, key)),
                "n_points": len(points),
                "p_value": float(result.pvalues["theta"]),
                "r_squared": float(result.rsquared),
                "slope": float(result.params["theta"]),
                "intercept": float(result.params["const"]),
            }
        )
    return pd.DataFrame.from_records(
        records,
        columns=[
            *GROUP_COLUMNS,
            "n_points",
            "p_value",
            "r_squared",
            "slope",
            "intercept",
        ],
    )


def plot_figure(
    data: Any,
    regressions: Any,
    png_path: Path,
    svg_path: Path,
    dpi: int,
    np: Any,
    plt: Any,
    sns: Any,
) -> None:
    from matplotlib.lines import Line2D
    from statsmodels.nonparametric.smoothers_lowess import lowess

    sns.set_theme(style="whitegrid", context="paper")
    figure, axes = plt.subplots(
        1, 3, figsize=(10.8, 3.2), constrained_layout=True
    )
    scatter_ax, p_value_ax, r_squared_ax = axes

    # Repeats do not add information to this deterministic metric.
    plot_data = data.drop_duplicates(
        subset=[*GROUP_COLUMNS, "theta", "normalized_levels"]
    )
    sns.scatterplot(
        data=plot_data,
        x="theta",
        y="normalized_levels",
        color="#808080",
        s=22,
        alpha=0.65,
        linewidth=0,
        ax=scatter_ax,
    )
    try:
        sns.kdeplot(
            data=plot_data,
            x="theta",
            y="normalized_levels",
            levels=8,
            color="#1976c9",
            linewidths=1.1,
            fill=False,
            thresh=0.03,
            ax=scatter_ax,
        )
    except (ValueError, np.linalg.LinAlgError):
        # A constant hierarchy depth has a singular 2D KDE. The scatter and
        # LOWESS still communicate the available result.
        pass

    smoothed = lowess(
        plot_data["normalized_levels"],
        plot_data["theta"],
        frac=0.35,
        return_sorted=True,
    )
    scatter_ax.plot(
        smoothed[:, 0],
        smoothed[:, 1],
        color="red",
        linewidth=1.5,
    )
    scatter_ax.set_xlim(-0.05, 1.05)
    scatter_ax.set_ylim(-0.25, 1.25)
    scatter_ax.set_xlabel(r"$\theta$")
    scatter_ax.set_ylabel("normalized # levels")
    scatter_ax.legend(
        handles=[
            Line2D(
                [],
                [],
                marker="o",
                linestyle="none",
                color="#808080",
                alpha=0.65,
                markersize=4,
                label="scatter",
            ),
            Line2D([], [], color="red", linewidth=1.5, label="LOWESS"),
            Line2D(
                [], [], color="#1976c9", linewidth=1.1, label="KDE"
            ),
        ],
        loc="upper left",
        frameon=True,
    )

    if regressions.empty:
        for axis in (p_value_ax, r_squared_ax):
            axis.text(
                0.5,
                0.5,
                "No varying test cases",
                ha="center",
                va="center",
                transform=axis.transAxes,
            )
    else:
        positive_p_values = regressions.loc[
            regressions["p_value"] > 0, "p_value"
        ]
        if positive_p_values.empty:
            p_value_ax.text(
                0.5,
                0.5,
                "p-values underflowed to zero",
                ha="center",
                va="center",
                transform=p_value_ax.transAxes,
            )
        else:
            sns.histplot(
                positive_p_values,
                bins="auto",
                stat="density",
                log_scale=True,
                color="#2f7fb7",
                edgecolor="#303030",
                linewidth=0.6,
                ax=p_value_ax,
            )

        sns.histplot(
            regressions["r_squared"],
            bins="auto",
            stat="density",
            color="#2f7fb7",
            edgecolor="#303030",
            linewidth=0.6,
            ax=r_squared_ax,
        )

    p_value_ax.set_xlabel(r"$p$-value")
    p_value_ax.set_ylabel("density")
    r_squared_ax.set_xlabel(r"$R^2$")
    r_squared_ax.set_ylabel("density")
    figure.suptitle(r"Regression results ($\theta$ vs #levels)", fontsize=14)

    png_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(png_path, dpi=dpi, bbox_inches="tight")
    figure.savefig(svg_path, bbox_inches="tight")
    plt.close(figure)


def settings_report(
    data: Any, regressions: Any, constant_depth: bool
) -> dict[str, Any]:
    warnings = []
    if len(data["theta"].unique()) < 10:
        warnings.append(
            "The theta grid is sparse relative to the paper experiment."
        )
    if constant_depth:
        warnings.append(
            "All selected trials have the same hierarchy depth."
        )
    if regressions.empty:
        warnings.append(
            "No test case had both at least three theta values and varying "
            "hierarchy depth, so the regression histograms are empty."
        )

    return {
        "rows": len(data),
        "splits": sorted(data["split"].unique().tolist()),
        "patterns": sorted(data["pattern"].unique().tolist()),
        "epsilon_values": sorted(data["epsilon"].unique().tolist()),
        "refinements": sorted(data["refinement"].unique().tolist()),
        "theta_values": sorted(data["theta"].unique().tolist()),
        "n_levels_min": int(data["n_levels"].min()),
        "n_levels_max": int(data["n_levels"].max()),
        "regression_test_cases": len(regressions),
        "warnings": warnings,
    }


def main() -> None:
    args = parse_args()
    np, pd, plt, sns, _ = import_plotting_packages()
    data = load_reports(args.dataset_root, args.include_splits, pd)
    data, constant_depth = add_normalized_levels(data)
    regressions = regression_by_test_case(data, pd)
    report = settings_report(data, regressions, constant_depth)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    regression_path = args.output_dir / "regression_stats.csv"
    settings_path = args.output_dir / "settings_report.json"
    png_path = args.output_dir / args.figure_name
    svg_path = args.output_dir / args.svg_name

    regressions.to_csv(regression_path, index=False)
    settings_path.write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    plot_figure(
        data,
        regressions,
        png_path,
        svg_path,
        args.dpi,
        np,
        plt,
        sns,
    )

    print(f"Wrote {png_path}")
    print(f"Wrote {svg_path}")
    print(f"Wrote {regression_path}")
    print(f"Wrote {settings_path}")
    for warning in report["warnings"]:
        print(f"WARNING: {warning}")


if __name__ == "__main__":
    main()
